# Generated by Django 4.2.4 on 2023-09-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0006_customeraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="default_address",
            field=models.BooleanField(default=False),
        ),
    ]
